openlvc/portico

- codebase/resources/dist/common/RTI.rid
- codebase/src/java/portico/org/portico/bindings/jgroups/Auditor.java
- codebase/src/java/portico/org/portico/bindings/jgroups/JGroupsProperties.java
- codebase/src/java/portico/org/portico/bindings/jgroups/MessageReceiver.java
- codebase/src/java/portico/org/portico/bindings/jgroups/channel/FederationChannel.java
Added a message audit log feature that when enabled in the RID will print information about each message sent and received by a federate. Information includes the direction, type of message, size, etc... Some summary information is also included at the conclusion. Sample output looks like below (taken from the end of an audit file put together on a test run:
```
received 15:13:28.434                   DeleteObject    213   from unknown(2)
received 15:13:28.434                   DeleteObject    213   from unknown(2)
received 15:13:28.434                   DeleteObject    213   from unknown(2)
received 15:13:28.435                   DeleteObject    213   from unknown(2)
received 15:13:28.435                   DeleteObject    213   from unknown(2)
received 15:13:28.435 …
```
> PORT-184 Message Size Logging

- codebase/resources/dist/common/RTI.rid
- codebase/src/java/portico/org/portico/bindings/jgroups/Auditor.java
- codebase/src/java/portico/org/portico/bindings/jgroups/JGroupsProperties.java
PORT-187, #58
This PR adds support to the JGroups auditor to include:
* FOM-specific information in log messages (object/interaction class, object name/id, attribute/param counts)
* FOM-specific summary (breaks down messages by both type, and object/interaction class)
* Filtering (can restrict the messages the auditor will log)
> Audit Logging Extensions (FOM-Specific Info and Filtering)

- codebase/profiles/linux/hla13.xml
- codebase/profiles/macosx/dlc13.xml
- codebase/profiles/macosx/hla13.xml
- codebase/profiles/macosx/test13.xml
- codebase/profiles/windows/hla13.xml
- codebase/src/java/portico/org/portico/impl/cpp13/NativeLibraryLoader.java
PORT-186 #59 Updated the build system to produce HLA 1.3 binaries with the suffix "_64" rather than just "64". Also updated the native library loader (which loads the native libraries into the java space to support calling back across the boundary for C++ federates). Tested and working on the Mac. Travis will test Linux and I'll manually test Windows.
> HLA 1.3 64-bit DLLs named with suffix _64

- codebase/profiles/macosx/hla13.xml
- codebase/profiles/macosx/test13.xml
- codebase/src/cpp/hla13/test/common/Common.cpp
- codebase/src/cpp/hla13/test/common/Common.h
- codebase/src/cpp/hla13/test/common/Test13Federate.cpp
- codebase/src/cpp/hla13/test/common/Test13Federate.h
- codebase/src/cpp/hla13/test/common/Test13FederateAmbassador.cpp
- codebase/src/cpp/hla13/test/common/Test13FederateAmbassador.h
- codebase/src/cpp/hla13/test/saverestore/FederationRestoreTest.cpp
- codebase/src/cpp/hla13/test/saverestore/FederationRestoreTest.h
- codebase/src/cpp/hla13/test/saverestore/FederationSaveTest.cpp
- codebase/src/cpp/hla13/test/saverestore/FederationSaveTest.h
- codebase/src/cpp/hla13/test/synchronization/RegisterSyncPointTest.cpp
- codebase/src/cpp/hla13/test/types/AttributeHandleValuePairSetTest.cpp
- codebase/src/cpp/hla13/test/types/ParameterHandleValuePairSetTest.cpp
This PR has been raised in response to https://github.com/openlvc/portico/issues/99
The warnings were being generated on OSX due to clang's adherance to the c++11 standard. C++11 has deprecated the assignment of a non-const char* variable to a string literal
- char* params in all test related functions have been analysed and converted to const char* where appropriate
- The `MAP_LTSTR_CLEANUP` macro in Common.h has been modified to work with a `map<const char*,const char*>`
- The `SET_LTSTR_CLEANUP` in Common.h has been modified to work with a `set<const char*>`
- Modified `Test13Federate::quickReflectFai`l to handle situation where the provided const char* tag parameter is `NULL`
- Modified `Test13Federate::quickSendFail` to handle situation where the provided const char* tag parameter is …
> PORT-99 HLA13 cpp tests no longer cause deprecated string transform warnings

- codebase/src/cpp/hla13/src/jni/Runtime.cpp
Part 2 (hopefully of 2) PR for https://github.com/openlvc/portico/issues/99
- Modified generateUnixPath() function to exclusively use strings instead of char*
- No string warnings under OSX and Windows
> PORT-99 Fixed missed deprecated string transform in Runtime.cpp

- codebase/src/java/portico/org/portico/bindings/jgroups/channel/FederationListener.java
This PR has been raised in response to issue https://github.com/openlvc/portico/issues/126#issuecomment-74778102
- Confirmed that `FederateListener.acceptView(View)` is called when the underlying JGroups mechanism confirms (not suspects) that a node has crashed
- Previously `FederateListener.acceptView(View)` was synthesising a `ResignFederation` message for each crashed federate, but never dispatching them to the LRC for processing.
- The resign messages are now forwarded on internally with a call to `FederateListener.receive()`
I've tested this under MacOS. The remaining federate takes a short time to announce it suspects the crash via the log, and then another short while to confirm it. After that execution resumes as normal.
Example output from the remaining federate is here:
```
INFO …
```
> PORT-126 Resign message now forwarded to LRC when a federate crash is confirmed

- codebase/profiles/windows/hla13.xml
- codebase/src/cpp/hla13/test/common/ActiveSR.cpp
- codebase/src/cpp/hla13/test/common/ActiveSR.h
- codebase/src/cpp/hla13/test/common/Test13FederateAmbassador.cpp
- codebase/src/cpp/hla13/test/ddm/RequestUpdateWithRegionTest.cpp
This PR has been raised in response to issue https://github.com/openlvc/portico/issues/124#issuecomment-74625037
The following work has been completed
- Found that the exec task that runs the hla13 test suite was setting the `PATH` env variable to `${hla13.complete.dir}`, however the actual compiled lib exists at `${hla13.complete.dir}\vc10`
- Added vc10 subdir to the `PATH` variable and the suite now executes
- `DEBUG` linker flag is now set when the test suite is compiled
- Test suite now links against a debug version of cppunit under Windows
- Heap corruption was happening in the test utility class `ActiveSR` due when the char* label memory was deleted at some stage. I've converted it into a std::string so all memory management issue magically disappear! (spiritfingers)
- Fixed an …
> PORT-124 hla13 tests dont compile under Windows

- codebase/resources/installers/windows/nsis/installer-win32.nsi
- codebase/resources/installers/windows/nsis/installer-win64.nsi
Forgot to include the bit where the uninstaller registry keys are removed on uninstall :)
> PORT-132 Uninstaller entries now deleted on uninstall

- codebase/src/java/portico/org/portico/lrc/model/datatype/DatatypeHelpers.java
- Copy/paste error lead to HLAinteger32BE being declared twice in the code that automatically injects standard MIM datatypes into the FOM
- Fixed typo so that HLAinteger64BE is now defined with the proper traits
> PORT-212 Fixes typo that left HLAinteger64BE undefined in the FOM

- codebase/src/cpp/ieee1516e/example/win32-vc14.bat
- codebase/src/cpp/ieee1516e/example/win64-vc14.bat
- codebase/src/cpp/ieee1516e/src/jni/Runtime.cpp
- codebase/src/java/portico/org/portico/impl/hla1516/fomparser/FOM.java
- codebase/src/java/portico/org/portico/impl/hla1516e/fomparser/FOM.java
- codebase/src/java/portico/org/portico/lrc/model/ACMetadata.java
- codebase/src/java/portico/org/portico/lrc/model/ObjectModel.java
- codebase/src/java/portico/org/portico/lrc/model/PCMetadata.java
- codebase/src/java/portico/org/portico/lrc/model/datatype/Dimension.java
- codebase/src/java/portico/org/portico/lrc/model/datatype/linker/DatatypePlaceholder.java
- codebase/src/java/portico/org/portico/lrc/model/datatype/linker/EnumeratorPlaceholder.java
- codebase/src/java/portico/org/portico/lrc/model/datatype/linker/Linker.java
- codebase/src/java/portico/org/portico/lrc/services/federation/handlers/outgoing/CreateFederationHandler.java
- codebase/src/java/test/hlaunit/ieee1516e/fom/Hla1516eFomParserTest.java
This PR has been submitted for bug ticket #256 
- When we initially developed the datatype parsing system, we worked under the assumption that all FOM modules were standalone in their own right - e.g. the datatypes has declarations for all datatypes that are referenced in the module.
- However in the modular RPRv2 FOM this is not the case. Datatypes, attributes and parameters can all reference datatypes that are declared soley in other FOM modules.
- As such a DatatypePlaceholder is now placed for all datatype links at parse time. Linking is deferred until all FOM modules have been parsed and merged, and the standard MIM has been inserted.
- Updated parsing unit tests to perform the delayed linking process.
*Note:* Branch has been merged off the PORT-254 branch.
> PORT-256 Defer linking until all FOM modules have been parsed and merged

- codebase/src/java/portico/org/portico/lrc/model/OCMetadata.java
- codebase/src/java/portico/org/portico/lrc/model/ObjectModel.java
- codebase/src/java/test/hlaunit/hla13/support/HandleFetchingTest.java
- codebase/src/java/test/hlaunit/ieee1516/support/PrivilegeToDeleteTest.java
- codebase/src/java/test/hlaunit/ieee1516e/federation/CreateFederationTest.java
- codebase/src/java/test/hlaunit/ieee1516e/support/PrivilegeToDeleteTest.java
PR Submitted for issue PORT-258
- Renamed incorrectly name `privilegeToDelete` to IEEE1516e compliant `privilegeToDeleteObject`
- Updated all unit tests
> PORT-258 privilegeToDelete renamed to privilegeToDeleteObject

- codebase/src/java/portico/org/portico/bindings/jgroups/JGroupsConnection.java
- codebase/src/java/portico/org/portico/bindings/jvm/JVMConnection.java
- codebase/src/java/portico/org/portico/impl/hla1516e/types/HLA1516eHandle.java
- codebase/src/java/portico/org/portico/lrc/model/Mom.java
- codebase/src/java/portico/org/portico/lrc/model/XmlRenderer.java
- codebase/src/java/portico/org/portico/lrc/services/federation/handlers/outgoing/CreateFederationHandler.java
- codebase/src/java/portico/org/portico/lrc/services/federation/handlers/outgoing/JoinFederationHandler.java
- codebase/src/java/portico/org/portico/lrc/services/mom/data/MomFederate.java
- codebase/src/java/portico/org/portico/lrc/services/mom/data/MomFederation.java
- codebase/src/java/portico/org/portico2/common/services/federation/msg/CreateFederation.java
- codebase/src/java/portico/org/portico2/common/services/federation/msg/JoinFederation.java
- codebase/src/java/portico/org/portico2/lrc/services/federation/outgoing/CreateFederationHandler.java
- codebase/src/java/portico/org/portico2/lrc/services/federation/outgoing/JoinFederationHandler.java
- codebase/src/java/portico/org/portico2/rti/RtiInbox.java
- codebase/src/java/portico/org/portico2/rti/federation/Federate.java
- codebase/src/java/portico/org/portico2/rti/federation/Federation.java
- codebase/src/java/portico/org/portico2/rti/services/federation/incoming/JoinFederationHandler.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/FomModule.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/MomEncodingHelpers.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/MomFederate.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/MomFederation.java
- codebase/src/java/portico/org/portico2/rti/services/mom/incoming/MomSendInteractionHandler.java
Work completed for Portico ticket #236.
- Fixed decoding of `HLA1516eHandle` through the static decode methods
- Corrected spelling of `HLAfederation.HLArequest.HLArequestFOMmoduleData` parameter `HLAFOMmoduleIndicator`
- `CreateFederation` and `JoinFederation` objects now contain the unparsed content of each FOM module that they were called with
* This data is included to support `HLArequestFOMmoduleDesignatorList` and `HLArequestFOMmoduleData` interactions
* Data is saved against the `Federation` and `Federate` object models
* Will likely need to be parsed within the `JoinFederation` handler so that the unified federation ObjectModel can be extended
- Added support for the `HLAmanager.HLAfederation` attributes `HLAFOMmoduleDesignatorList` and `HLAcurrentFDD`
- Added support for the …
> Adds support for MOM Request/Report Object Model Data interactions

- codebase/src/java/portico/org/portico2/common/services/pubsub/data/InterestManager.java
- codebase/src/java/portico/org/portico2/rti/federation/FederateMetrics.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/InteractionCount.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/InteractionSubscription.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/MomEncodingHelpers.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/MomFederate.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/MomManager.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/ObjectClassBasedCount.java
- codebase/src/java/portico/org/portico2/rti/services/mom/incoming/MomSendInteractionHandler.java
- codebase/src/java/portico/org/portico2/rti/services/mom/incoming/MomUpdateAttributesHandler.java
- codebase/src/java/portico/org/portico2/rti/services/object/incoming/DeleteObjectHandler.java
- codebase/src/java/portico/org/portico2/rti/services/object/incoming/RegisterObjectHandler.java
- codebase/src/java/portico/org/portico2/rti/services/pubsub/incoming/SubscribeObjectClassHandler.java
This PR contains work done for tickets #231, #232, #233 and #234 
- Adds support for `HLAfederate.HLArequest.HLArequestPublications` and its corresponding response interactions `HLAfederate.HLAreport.HLAreportObjectClassPublication` and `HLAfederate.HLAreport.HLAreportInteractionPublication`
- Adds support for `HLAfederate.HLArequest.HLArequestSubscriptions` and its corresponding response interactions `HLAfederate.HLAreport.HLAreportObjectClassSubscription` and
`HLAfederate.HLAreport.HLAreportInteractionSubscription`
- Adds support for MOM interaction `HLAfederate.HLArequest.HLArequestObjectInstancesThatCanBeDeleted` and its
corresponding response `HLAfederate.HLAreport.HLAreportObjectInstancesThatCanBeDeleted`
- Adds support for MOM interaction …
> Adds MOM interaction support for object and interaction metrics

- codebase/src/java/portico/org/portico/lrc/PorticoConstants.java
- codebase/src/java/portico/org/portico/lrc/services/object/handlers/outgoing/RequestObjectUpdateHandler.java
- codebase/src/java/portico/org/portico2/lrc/services/mom/incoming/SetServiceReportingHandler.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/MomEncodingHelpers.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/MomManager.java
- codebase/src/java/portico/org/portico2/rti/services/mom/incoming/MomSendInteractionHandler.java
- codebase/src/java/test/hlaunit/hla13/mom/MomFederationTest.java
- codebase/src/java/test/hlaunit/hla13/ownership/QueryOwnershipTest.java
- codebase/src/java/test/hlaunit/ieee1516/mom/MomFederationTest.java
- codebase/src/java/test/hlaunit/ieee1516e/common/Abstract1516eTest.java
- codebase/src/java/test/hlaunit/ieee1516e/common/TestFederateAmbassador.java
- codebase/src/java/test/hlaunit/ieee1516e/common/TestInteraction.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomExceptionReportingTest.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomFederateLifecycleTest.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomFederationTest.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomObjectModelTest.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomRequestInteractionMetricsTest.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomRequestObjectMetricsTest.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomRequestPublicationsTest.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomRequestSubscriptionsTest.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomRequestSynchronizationPoints.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomServiceReportingTest.java
- Added some remedial unit tests for the newly supported MOM interactions
- `HLAreportMomException` fixed so that it now includes the `HLAfederate` parameter, populated with handle of the federate that invoked the service
- `HLAreportObjectInstanceInformation` now returns a `HLAknownClass` value of `ObjectModel.INVALID_HANDLE` if the context federate owns the object but has not discovered it
- `HLAreportSynchronizationPoints` now only returns sync points that are "in-progress" as per the spec
> Added MOM interaction unit tests and fixed resulting bugs

- codebase/src/java/portico/org/portico2/rti/RtiInbox.java
- codebase/src/java/portico/org/portico2/rti/cli/EnvironmentVariables.java
- codebase/src/java/portico/org/portico2/rti/cli/RtiCli.java
- codebase/src/java/portico/org/portico2/rti/cli/command/ChangeContext.java
- codebase/src/java/portico/org/portico2/rti/cli/command/CommandFactory.java
- codebase/src/java/portico/org/portico2/rti/cli/command/CreateFederation.java
- codebase/src/java/portico/org/portico2/rti/cli/command/Echo.java
- codebase/src/java/portico/org/portico2/rti/cli/command/ICommand.java
- codebase/src/java/portico/org/portico2/rti/cli/command/ListContextContents.java
- codebase/src/java/portico/org/portico2/rti/cli/command/ListEnvironmentVariables.java
- codebase/src/java/portico/org/portico2/rti/cli/command/MomInfo.java
- codebase/src/java/portico/org/portico2/rti/cli/command/PubInfo.java
- codebase/src/java/portico/org/portico2/rti/cli/command/RemoveContext.java
- codebase/src/java/portico/org/portico2/rti/cli/command/RtiInfo.java
- codebase/src/java/portico/org/portico2/rti/cli/command/Shutdown.java
- codebase/src/java/portico/org/portico2/rti/cli/command/SubInfo.java
- codebase/src/java/portico/org/portico2/rti/cli/fs/FSContext.java
- codebase/src/java/portico/org/portico2/rti/cli/fs/FSContextFactory.java
- codebase/src/java/portico/org/portico2/rti/federation/Federate.java
- codebase/src/java/portico/org/portico2/rti/federation/FederateMetrics.java
- codebase/src/java/portico/org/portico2/rti/federation/Federation.java
- codebase/src/java/portico/org/portico2/rti/services/RTIMessageHandler.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/MomFederate.java
- codebase/src/java/portico/org/portico2/rti/services/mom/data/MomManager.java
- codebase/src/java/portico/org/portico2/rti/services/object/incoming/DeleteObjectHandler.java
- `RtiInbox` now checks if the source federate that a "Federation" message is from is currently joined to that federation before handing the message off to the message sink for processing
- This prevents processing of messages from Federates that have been force resigned by external means (E.g. the console)
- Removed stale Federate member timeStatus
- Updated all references to query the Federation's time manager instead (which is kept up to date)
- Added pseudo file system and command handling to the skeleton CLI
> Joined check on RTI-side Federation message handlers #276

- codebase/src/java/portico/org/portico/impl/hla1516e/Rti1516eAmbassador.java
- codebase/src/java/portico/org/portico/lrc/model/ModelMerger.java
- codebase/src/java/portico/org/portico/lrc/services/federation/handlers/outgoing/CreateFederationHandler.java
- codebase/src/java/portico/org/portico/lrc/services/federation/msg/CreateFederation.java
- codebase/src/java/test/hlaunit/ieee1516e/federation/CreateFederationTest.java
Attempts to create a federation execution with a null for the FOM modules parameter failed with a `NullPointerException`, and with an empty FOM modules array caused an `IndexOutOfBoundsException`.
A few places in the code caused this, depending on which version/method signature of the `createFederationExecution` method is invoked, but they all basically came down to an assumption that the `fomModules` parameter is never a null or empty array. These are...
`org.portico.lrc.services.federation.msg.CreateFederation`:
- Added checks for a `null` URL (or URLs) in 3 constructor variants before processing to avoid `NullPointerException`
`org.portico.impl.hla1516e.Rti1516eAmbassador#createFederationExecution( String federationName, URL[] fomModules, URL mimModule )`:
- added check for null …
> Fix for Issue #286: Creating a Federation Execution with a `null` or empty FOM array throws NullPointerException/IndexOutOfBoundsException

- codebase/src/java/portico/org/portico/lrc/model/ModelMerger.java
- codebase/src/java/portico/org/portico/lrc/model/OCMetadata.java
Replaces several uses of HashSets with TreeSets in/around OCMetaData
Previously Hashset were used for adding in objects from FOMs,
however the order that objects returned by the iterator is not
fixed, so different federates could add objects in different orders,
causing handle mismatches. TreeSets however will always return the same
set in the same order, so no handle mismatches.
> Fix combining multiple FOMs

- codebase/src/java/portico/org/portico2/rti/services/object/incoming/RegisterObjectHandler.java
The RegisterObjectHandler sends a ManyCast message to all subscribed federates when a new object is created. The producing federate is removed from the list of subscribed federates, to prevent it from receiving a Discover message on its own objects. However, if no other federates subscribe to the object class, the list of subscribers is empty. The queueManycast method takes an empty list of recipients to mean that the message should be broadcast to everybody, meaning the producing federate will receive a DiscoverObject call on its own object. Fixed by adding a check to avoid sending the DiscoverObject message when the list of recipients is empty.
> Stop producing federate from receiving DiscoverObjectCalls on its own object

- codebase/src/java/portico/org/portico/impl/hla1516e/handlers2/ProvideUpdateCallbackHandler.java
Currently, ProvideAttributeValueUpdate callbacks seem to be delivered to all connected federates, even though they don't own any attributes of the object in question. Added a check that only delivers the callback for attributes that are actually owned by the federate, and doesn't deliver the callback if no attributes are owned.
> Only deliver ProvideAttributeValueUpdate callbacks to the owning federate

- codebase/resources/dist/common/RTI.rid
- codebase/resources/jars/portico.jar/etc/jgroups-udp.xml
- codebase/src/java/examples/hla13/RTI.rid
- codebase/src/java/examples/ieee1516e/RTI.rid
Message bundling is enabled by default, and the default timeout is 30ms. This value is too high for all but the most chatty federations, and has the impact of increasing default latency. Reducing it down to 5ms feels like it balances responsiveness with a desire to not generate a packet flood on networks.
Fix: #349
> Reduce message bundling default timeout from 30ms to 5ms

- codebase/src/java/examples/event-logger/linux.sh
- codebase/src/java/examples/event-logger/win32.bat
- codebase/src/java/examples/hla13/linux.sh
- codebase/src/java/examples/hla13/windows.bat
- codebase/src/java/examples/hla13java1/linux.sh
- codebase/src/java/examples/hla13java1/windows.bat
- codebase/src/java/examples/ieee1516e/linux.sh
- codebase/src/java/examples/ieee1516e/windows.bat
This isn't strictly necessary, but without it <javac> will issue warnings. We have lots of libraries on the classpath that use annotation processing, so this warning will forever pop up. The least we can do is show how to get rid of the warning. Without annotation processing the RTI as it exists today may well break (won't be able to discover handlers), so it can't hurt to just enable it explicitly.
> Update example scripts so javac calls enable annotation processing

- .classpath
- codebase/src/java/test/hlaunit/ieee1516e/common/TestFederate.java
- codebase/src/java/test/hlaunit/ieee1516e/federation/FederationConsistencyTest.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomModelMergingTest.java
Adds test cases that check for a consistency view of the federation across multiple federates. Initially this is just focused on handle generation for all FOM modules.
> Federate Consistency Checks

- codebase/src/java/portico/org/portico/bindings/jgroups/Federation.java
- codebase/src/java/portico/org/portico/lrc/LRCState.java
- codebase/src/java/test/hlaunit/ieee1516e/federation/FederationConsistencyTest.java
The FOM is set in the LRCState when a federate joins a federation. If another federate subsequently joins the federation and extends the FOM, and it happens to add modules, peer JGroups federate would never have their local FOM updated, so they never knew the new types existed.
This update fixes that and pushes in new object models received as a result of remote peer joins.
Working: #188
> Fix bug preventing JGroups federates from updating FOMs after peer join

- .classpath
- codebase/src/java/portico/org/portico/bindings/jgroups/Federation.java
- codebase/src/java/portico/org/portico/lrc/LRCState.java
- codebase/src/java/test/hlaunit/ieee1516e/common/TestFederate.java
- codebase/src/java/test/hlaunit/ieee1516e/federation/FederationConsistencyTest.java
- codebase/src/java/test/hlaunit/ieee1516e/mom/MomModelMergingTest.java
Added tests for consistenct views of the FOM from across all participants in a federation. This identified a bug where once a federate had joined, the FOM was no longer updated, so it would not see extensions brought in by later joining federates.
Commit also addresses that issue with the test confirmed in the JGroups binding (with a sad, hacked fix).
> Fix FOM-view consistency across a federation.

- codebase/src/java/portico/hla/rti1516e/LogicalTimeFactoryFactory.java
- codebase/src/java/portico/hla/rti1516e/RtiFactoryFactory.java
The 1516e spec made some questionable decisions around using SPI classes for things other than what they were designed for. This caused things to break post Java 9. This borrows the spec from HLA4 for the two impacted classes, which resolves this issue.
> Update the 1516e spec classes to be Java 21 compatible
